server:
  port: 9090
spring:
  application:
    name: Aston
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: q123w456erd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
